version: '3.8'

services:
  apache-php:
    build: ./apache-php
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - ./apache-php.conf:/etc/apache2/conf-available/servername.conf  # Asegúrate de que esto sea correcto
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: my_database
    networks:
      - backend

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: my_database
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

networks:
  backend:
    driver: bridge
